apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: traffic-routing
  namespace: default
spec:
  template:
    metadata:
      name: traffic-routing-v1
    spec:
      containers:
        - name: user-container
          image: gcr.io/knative-samples/helloworld-go:latest
          env:
            - name: TARGET
              value: "v1 (stable)"
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
