---
apiVersion: v1
kind: Namespace
metadata:
  name: knative-serving
  labels:
    app.kubernetes.io/name: knative-serving
---
apiVersion: v1
kind: Namespace
metadata:
  name: knative-eventing
  labels:
    app.kubernetes.io/name: knative-eventing
---
apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
  labels:
    app.kubernetes.io/name: knative-serving
    app.kubernetes.io/component: serving
    app.kubernetes.io/part-of: knative
spec:
  version: "1.19.7"
  ingress:
    kourier:
      enabled: true
  config:
    network:
      ingress-class: "kourier.ingress.networking.knative.dev"
  high-availability:
    replicas: 1
  workloads:
    - name: activator
      replicas: 1
      resources:
        - container: activator
          requests:
            cpu: 300m
            memory: 60Mi
          limits:
            cpu: 1000m
            memory: 600Mi
    - name: autoscaler
      replicas: 1
      resources:
        - container: autoscaler
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 1000m
            memory: 1000Mi
    - name: controller
      replicas: 1
      resources:
        - container: controller
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 1000m
            memory: 1000Mi
    - name: webhook
      replicas: 1
      resources:
        - container: webhook
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 500m
            memory: 500Mi
---
apiVersion: operator.knative.dev/v1beta1
kind: KnativeEventing
metadata:
  name: knative-eventing
  namespace: knative-eventing
  labels:
    app.kubernetes.io/name: knative-eventing
    app.kubernetes.io/component: eventing
    app.kubernetes.io/part-of: knative
spec:
  version: "1.19.7"
  high-availability:
    replicas: 1
  workloads:
    - name: eventing-controller
      resources:
        - container: eventing-controller
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 1000m
            memory: 1000Mi
    - name: eventing-webhook
      resources:
        - container: eventing-webhook
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 500m
            memory: 500Mi
